/*--*//*@formatter:off*//*--*//*++[[PACKAGE]]++*//*--*/package io.github.tezch.atomsql.processor;/*--*/

import javax.annotation.processing.Generated;

/*--*/import io.github.tezch.atomsql.annotation.processor.Method;/*--*//*++[[IMPORT_METHOD_CLASS]]++*/
import io.github.tezch.atomsql.annotation.processor.Methods;

// This class was generated by Atom SQL. Do not modify this file manually.
@Generated("[[GENERATED]]")
@SuppressWarnings("javadoc")
/*++@Methods({[[METHODS]]})++*//*--*/@Methods({ @Method(name = "", parameters = {}, parameterTypes = {}) })/*--*/
public interface /*--*/AtomSqlMetadata_Template/*--*//*++[[INTERFACE]]++*/ {}
