/*--*//*@formatter:off*//*--*//*++[[PACKAGE]]++*//*--*/package io.github.tezch.atomsql.processor;/*--*/

import javax.annotation.processing.Generated;

import io.github.tezch.atomsql.annotation.DataObject;

//This class was generated by Atom SQL. Do not modify this file manually.
@Generated("[[GENERATED]]")
@DataObject
@SuppressWarnings("javadoc")
public record /*--*/DataObject_Template/*--*//*++[[CLASS]]++*/(
/*++[[COLUMNS]]++*/
) {}
