/*--*//*@formatter:off*//*--*//*++[[PACKAGE]]++*//*--*/package io.github.tezch.atomsql.processor;/*--*/

import javax.annotation.processing.Generated;

import io.github.tezch.atomsql.annotation.processor.OptionalData;
import io.github.tezch.atomsql.annotation.processor.OptionalDatas;

//This class was generated by Atom SQL. Do not modify this file manually.
@Generated("[[GENERATED]]")
@SuppressWarnings("javadoc")
/*++@OptionalDatas({[[OPTIONAL_DATAS]]})++*//*--*/@OptionalDatas({ @OptionalData(name = "", type = Object.class )})/*--*/
public interface /*--*/DataObjectMetadata_Template/*--*//*++[[INTERFACE]]++*/ {}
