/*--*//*@formatter:off*//*--*//*++[[PACKAGE]]++*//*--*/package io.github.tezch.atomsql.processor;/*--*/

import javax.annotation.processing.Generated;

//This class was generated by Atom SQL. Do not modify this file manually.
@Generated("[[GENERATED]]")
@SuppressWarnings("javadoc")
public class /*--*/ParameterBinder_Template/*--*//*++[[CLASS]]++*/ {

	static { //Enum validation part
/*++[[ENUM_VALIDATORS]]++*/
	}

/*++[[FIELDS]]++*/
}
