/*--*//*@formatter:off*//*--*//*++[[PACKAGE]]++*//*--*/package io.github.tezch.atomsql.processor;/*--*/

import javax.annotation.processing.Generated;

import io.github.tezch.atomsql.annotation.DataObject;
import io.github.tezch.atomsql.annotation.processor.TooManyColumnsDataObject;

//This class was generated by Atom SQL. Do not modify this file manually.
@Generated("[[GENERATED]]")
@DataObject
@TooManyColumnsDataObject(bean = /*--*/TooManyColumnsDataObject_Template/*--*//*++[[CLASS]]++*/.Bean.class)
@SuppressWarnings("javadoc")
public class /*--*/TooManyColumnsDataObject_Template/*--*//*++[[CLASS]]++*/ {
	static { //Enum validation part
/*++[[ENUM_VALIDATORS]]++*/
	}

	public /*--*/TooManyColumnsDataObject_Template/*--*//*++[[CLASS]]++*/(Bean bean) {
/*++[[BEAN_TO_COLUMNS]]++*/
	}

/*++[[FIELDS]]++*/

/*++[[METHODS]]++*/

	public static class Bean {
/*++[[COLUMNS]]++*/
	}
}
