/*--*//*@formatter:off*//*--*//*++[[PACKAGE]]++*//*--*/package io.github.tezch.atomsql.processor;/*--*/

import javax.annotation.processing.Generated;

//This class was generated by Atom SQL. Do not modify this file manually.
@Generated("[[GENERATED]]")
@SuppressWarnings("javadoc")
public class /*--*/Unfolder_Template/*--*//*++[[CLASS]]++*/ {

/*++[[FIELDS]]++*/
}
